version: "3"

services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=business
      - POSTGRES_DB=business
      - TZ=Asia/Shanghai
      - PGTZ=Asia/Shanghai
      - ALLOW_IP_RANGE=0.0.0.0/0
  app:
    build: .
    working_dir: /app
    container_name: ddd-template
    command: ./server --config ${DT_CONFIG:-./configs/config.yaml}
    restart: always
    depends_on:
      - db
    ports:
      - "8818:8818"
    volumes:
      - ${DT_CONFIG:-./configs}:/app/configs
      - ./logs:/app/logs
      - ${DT_STATIC:-./static}/:/app/static/
