version: "3"

services:
  app:
    image: ddd-template/server
    working_dir: /app
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8818:8818"
    volumes:
      - ./configs/:/app/configs
      - ./log:/app/log
      - ${RESOURCE:-./resource}/:/app/resource/
