basePath: /api/v1
consumes:
- application/json
definitions:
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      message: {}
    type: object
  schema.DemoResp:
    properties:
      createdAt:
        description: 创建时间
        type: integer
      message:
        description: 消息
        type: string
    type: object
info:
  contact:
    email: olongfen@gmail.com
    name: olongfen
  description: demo
  title: demo
  version: "1.0"
paths:
  /demo/{id}:
    get:
      description: hello
      operationId: demo-get-one
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/schema.DemoResp'
              type: object
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: hello
      tags:
      - demo
produces:
- application/json
schemes:
- HTTP
- HTTPS
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
