version: "3"

services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=business
      - POSTGRES_DB=business
      - ALLOW_IP_RANGE=0.0.0.0/0
