database:
    automigrate: true
    dbname: business
    debug: true
    driver: postgresql
    host: 127.0.0.1
    password: business
    port: "5432"
    sslmode: disable
    timezone: Asia/Shanghai
    user: postgres
enablegraph: false
http:
    baseurl: ""
    host: 0.0.0.0
    port: "8818"
log:
    compress: true
    debug: true
    errorfile: ./log/server-err.log
    filename: ./log/server.log
    maxages: 30
    maxbackups: 50
    maxsize: 20
nacos:
    clientname: ""
    host: 127.0.0.1
    port: 10948
    register: false
    weight: 0
redis:
    addr: 127.0.0.1:6379
    db: 1
    keyprefix: system_manage
    password: "123456"
    use: true
rpc:
    host: 0.0.0.0
    port: 9060
watchconfig: false
