db:
    automigrate: true
    debug: true
    driver: postgresql
    dsn: host=localhost user=postgres password=business dbname=business port=5432 sslmode=disable TimeZone=Asia/Shanghai
enablegraph: false
http:
    ip: 0.0.0.0
    port: "8818"
log:
    compress: true
    debug: true
    errorfile: ./log/server-err.log
    filename: ./log/server.log
    maxages: 30
    maxbackups: 50
    maxsize: 20
nacos:
    clientip: 127.0.0.1
    host: 127.0.0.1
    port: 10948
    register: false
    weight: 0
redis:
    addr: 127.0.0.1:6379
    db: 1
    keyprefix: system_manage
    password: "123456"
    use: false
rpc:
    host: 0.0.0.0
    port: 9060
watchconfig: false
