server:
  http:
    host: 192.168.3.85
    port: 8990
    addr: 192.168.3.85:8818

database:
    driver: postgres
    source: postgres://business:business@192.168.3.85:54323/business?sslmode=disable
jaegerhost: 127.0.0.1
environment: dev
log:
  filename: ./log/ddd-template.log
  maxsize: 20
  maxbackups: 30
  maxages: 30
  compress: false

