server:
  http:
    host: 0.0.0.0
    port: 8818
    addr: 0.0.0.0:8818
  grpc:
    pemfile: ../../configs/server.crt
    keyfile: ../../configs/server.key
    tls: false
    host: 0.0.0.0
    port: 8918
    clients:
      -
        appid: "1"
        appkey: "123456"

database:
  driver: postgres
  source: postgres://postgres:business@0.0.0.0:5432/business?sslmode=disable
jaegerhost: 127.0.0.1
environment: dev
debug: true
log:
  filename: ./log/server-template.log
  errorfile: ./log/error.log
  maxsize: 20
  maxbackups: 30
  maxages: 30
  compress: false

