database:
    automigrate: true
    dbname: business
    debug: true
    driver: postgresql
    host: db
    password: business
    port: "5432"
    sslmode: disable
    timezone: Asia/Shanghai
    user: postgres
http:
    host: 0.0.0.0
    port: "8818"
languages:
    - cn
    - en
log:
    compress: true
    debug: false
    errorfile: ./log/server-err.log
    filename: ./log/server.log
    maxages: 30
    maxbackups: 50
    maxsize: 20
