server:
  http:
    host: 0.0.0.0
    port: 8818
    addr: 0.0.0.0:8818

database:
    driver: postgres
    source: postgres://postgres:123456@192.168.8.18:5432/postgres?sslmode=disable
jaegerhost: 127.0.0.1
environment: dev
log:
  filename: ./log/ddd-template.log
  maxsize: 20
  maxbackups: 30
  maxages: 30
  compress: false

