package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"ddd-template/internal/ports/graphql/graph/model"
	"fmt"
	uuid "github.com/satori/go.uuid"
)

// User is the resolver for the User field.
func (r *mutationResolver) User(ctx context.Context, username string) (*model.User, error) {
	return &model.User{UUID: uuid.NewV4().String(), Username: username}, nil
}

// User is the resolver for the User field.
func (r *queryResolver) User(ctx context.Context, uuid string) (*model.User, error) {
	return &model.User{UUID: uuid, Username: "hello graphql"}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *mutationResolver) Todo(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Todo - todo"))
}
func (r *queryResolver) Todo(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Todo - todo"))
}
