basePath: /
definitions:
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      errors: {}
      language:
        type: string
      message:
        type: string
    type: object
info:
  contact:
    email: olongfen@gmail.com
    name: olongfen
  description: 用户管理系统api文档
  title: documents
  version: "1.0"
paths:
  /api/v1/demo:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: hello world
      tags:
      - Demo
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
