definitions:
  v1.DemoInfo:
    properties:
      createdAt:
        description: 创建时间
        type: integer
      id:
        type: integer
      message:
        description: 消息
        type: string
      updatedAt:
        description: 更新时间
        type: integer
    type: object
  v1.GreeterHTTPServerResp:
    properties:
      code:
        type: integer
      data: {}
      message: {}
    type: object
info:
  contact: {}
paths:
  /api/v1/demo:
    get:
      consumes:
      - application/json
      description: sends a string msg
      parameters:
      - description: message
        in: query
        name: msg
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.GreeterHTTPServerResp'
            - properties:
                code:
                  type: integer
                data:
                  $ref: '#/definitions/v1.DemoInfo'
              type: object
      summary: say hello
      tags:
      - Demo
swagger: "2.0"
