definitions:
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      message: {}
    type: object
  schema.ClassAddForm:
    properties:
      name:
        description: 班级名称
        type: string
    required:
    - name
    type: object
  schema.StudentAddForm:
    properties:
      classUuid:
        description: 班级uuid
        type: string
      name:
        description: 姓名
        type: string
      stuNumber:
        description: 学号
        type: string
    required:
    - classUuid
    - name
    - stuNumber
    type: object
info:
  contact: {}
paths:
  /api/v1/classes:
    post:
      description: add
      operationId: class add one
      parameters:
      - description: form
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/schema.ClassAddForm'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: add class one record
      tags:
      - classes
  /api/v1/students:
    post:
      description: add
      operationId: student add one
      parameters:
      - description: form
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/schema.StudentAddForm'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: add student one record
      tags:
      - students
  /api/v1/students/{uuid}:
    get:
      description: get
      operationId: student one
      parameters:
      - description: uuid4
        in: path
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: get student one record
      tags:
      - students
swagger: "2.0"
