definitions:
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      errors: {}
      language:
        type: string
      message:
        type: string
    type: object
  schema.ClassAddForm:
    properties:
      name:
        description: 班级名称
        type: string
    required:
    - name
    type: object
  schema.ClassQueryResp:
    properties:
      list:
        items:
          $ref: '#/definitions/schema.ClassResp'
        type: array
      pagination:
        $ref: '#/definitions/schema.Pagination'
    type: object
  schema.ClassResp:
    properties:
      classUuid:
        description: class uuid
        type: string
      createdAt:
        $ref: '#/definitions/utils.JSONTime'
        description: 创建时间
      id:
        description: id
        type: integer
      name:
        description: 班级名称
        type: string
      updatedAt:
        $ref: '#/definitions/utils.JSONTime'
        description: 更新时间
    type: object
  schema.ClassUpForm:
    properties:
      name:
        description: update body
        type: string
    type: object
  schema.Pagination:
    properties:
      currentPage:
        type: integer
      pageSize:
        type: integer
      totalCount:
        type: integer
      totalPage:
        type: integer
    type: object
  schema.StudentAddForm:
    properties:
      classUuid:
        description: 班级uuid
        type: string
      name:
        description: 姓名
        type: string
      stuNumber:
        description: 学号
        maxLength: 10
        minLength: 1
        type: string
    required:
    - classUuid
    - name
    - stuNumber
    type: object
  schema.StudentResp:
    properties:
      className:
        description: 班级名称
        type: string
      classUuid:
        description: 班级uuid
        type: string
      createdAt:
        $ref: '#/definitions/utils.JSONTime'
        description: 创建时间
      id:
        description: ID
        type: integer
      name:
        description: 学生姓名
        type: string
      stuNumber:
        description: 学号
        type: string
      updatedAt:
        $ref: '#/definitions/utils.JSONTime'
        description: 更新时间
      uuid:
        description: Uuid
        type: string
    type: object
  schema.StudentUpForm:
    properties:
      classUuid:
        description: 班级uuid
        type: string
      name:
        description: Name 姓名
        type: string
    type: object
  schema.StudentsQueryResp:
    properties:
      list:
        items:
          $ref: '#/definitions/schema.StudentResp'
        type: array
      pagination:
        $ref: '#/definitions/schema.Pagination'
    type: object
  utils.JSONTime:
    properties:
      time.Time:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/classes:
    get:
      description: 分页查询class
      operationId: query class
      parameters:
      - collectionFormat: multi
        description: string order collection
        in: query
        items:
          type: string
        name: order
        type: array
      - collectionFormat: multi
        description: string sort collection
        in: query
        items:
          type: string
        name: sort
        type: array
      - in: query
        minimum: 0
        name: currentPage
        type: integer
      - in: query
        maximum: 100
        minimum: 1
        name: pageSize
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/schema.ClassQueryResp'
              type: object
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: 查询class
      tags:
      - classes
    post:
      description: add
      operationId: class add one
      parameters:
      - description: form
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/schema.ClassAddForm'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: add class one record
      tags:
      - classes
  /api/v1/classes/{id}:
    put:
      description: update class by id
      operationId: update class
      parameters:
      - description: form
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/schema.ClassUpForm'
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: update class
      tags:
      - classes
  /api/v1/students:
    get:
      description: get
      operationId: query students
      parameters:
      - in: query
        minimum: 0
        name: currentPage
        type: integer
      - in: query
        name: name
        type: string
      - in: query
        maximum: 100
        minimum: 1
        name: pageSize
        type: integer
      - collectionFormat: multi
        description: string order collection
        in: query
        items:
          type: string
        name: order
        type: array
      - collectionFormat: multi
        description: string sort collection
        in: query
        items:
          type: string
        name: sort
        type: array
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  $ref: '#/definitions/schema.StudentsQueryResp'
              type: object
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: query students
      tags:
      - students
    post:
      description: add
      operationId: student add one
      parameters:
      - description: form
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/schema.StudentAddForm'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: add student one record
      tags:
      - students
  /api/v1/students/{id}:
    get:
      description: get
      operationId: student one
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/schema.StudentResp'
              type: object
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: get student one record
      tags:
      - students
    put:
      description: 通过id更新一条学生记录
      operationId: student update one
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: update form
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/schema.StudentUpForm'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: 更新
      tags:
      - students
swagger: "2.0"
