package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"ddd-template/internal/application/schema"
	"github.com/satori/go.uuid"
)

// User is the resolver for the User field.
func (r *mutationResolver) User(ctx context.Context, username string) (*schema.User, error) {
	return &schema.User{UUID: uuid.NewV4().String(), Username: username}, nil
}

// User is the resolver for the User field.
func (r *queryResolver) User(ctx context.Context, uuid string) (*schema.User, error) {
	return &schema.User{UUID: uuid, Username: "hello graphql"}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
