package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"ddd-template/internal/application/schema"
	"fmt"
)

// CreateDemo is the resolver for the createDemo field.
func (r *mutationResolver) CreateDemo(ctx context.Context, input schema.NewDemo) (*schema.Demo, error) {
	panic(fmt.Errorf("not implemented: CreateDemo - createDemo"))
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context, msg string) (string, error) {
	return r.app.Query().Demo().Hello(ctx, msg), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
